version: "3"
services:
  mongodb:
    image: mongo:4.2.23-bionic
    environment:
      MONGO_INITDB_DATABASE: myDB
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - '27017:27017'